app = 'bloglist-rk2gnq-dawn-resonance-6647'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    type = "http"
    port = 3001
    path = "/api/health"
    interval = "30s"
    timeout = "5s"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
